apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-v78t
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-v78t@sha256:6f810dc2703fe32cdeb506d3b6f8303586653ece435eb2af7bceb99110a7a4de
        name: my-nodejs
        resources: {}
status: {}
